library(boot)
library(Rlab)
library(tidyverse)
options(digits=3)

source("HSR_simulation_fn.R", local = knitr::knit_global())
source("HSR_calib_fn.R", local = knitr::knit_global())

df <- make_regions(global_params)
df <- tibble::as_tibble(df)


# Demo of calibrated parameters -------------------------------------------

# Demonstrating average error across 50 runs 
# of calibration values generated by data from global_params
calib_avg(global_params, nruns=50, table=1)
calib_avg(global_params, nruns=50, table=2)
calib_avg(global_params, nruns=50, table=3)





# CODE for calibrating parameters in-line ---------------------------------
# Given a set of starting parameters start_params (using global_params below as example),
# use functions from HSR_calib_fn.R to explore parameter space and minimize calibration error.
start_params <- global_params


# Calibrating Table 1 -----------------------------------------------------
# Repeat until errors are sufficiently small
start_params <- calib_table1(start_params)  
print(calib_assist1(start_params))


# Calibrating Table 2 -----------------------------------------------------
new_params <- global_params

# Step 1: Search for best adjustment for beta.4
for(adjust1 in seq(0,.5,.1) ){
  new_params$beta.4= global_params$beta.4 + adjust1
  print(c(adjust1, calib_assist2(new_params)[1],  calib_assist2(new_params)[2]))
}

# Step 2: Adjust beta.4 in global_params accordingly to minimize error (not shown; done manually)

# Step 3: Search for best adjustments for beta.5
for(adjust1 in seq(0,.5,.1) ){
  new_params$beta.5= global_params$beta.5 + adjust1
  print(c(adjust1, calib_assist2(new_params)[3],  calib_assist2(new_params)[4]))
}

# Step 4: Adjust beta.5 in global_params accordingly to minimize error (not shown; done manually)

# Step 5: Repeat until Table 1 errors are sufficiently small


# Calibrating Table 3 -----------------------------------------------------
# Goal: minimize P(B=1|S=1, A=0), P(B=1|S=1, A=1) summed abs error

new_params = global_params

# Step 1: Search for the best adjustment of om.1/om.2 simultaneously. 
adjust_vals <- seq(-2,1,.5 )
n <- length(adjust_vals)
calib_errs <- matrix(NA, nrow = n, ncol = n)
for(i in c(1:n) ){
  for(j in c(1:n) ){
    new_params$om.1= global_params$om.1 + adjust_vals[i]
    new_params$om.2 = global_params$om.2 + adjust_vals[j]
    
    # minimizing summed absolute error of both targets
    calib_errs[i,j] = abs(calib_assist3(new_params)[1,2])+abs(calib_assist3(new_params)[2,2])
  }
}

# Step 2: find the adjustments which minimize error
# For example, in the above example round of adjustment (with an outdated global_params),
# we found that calib_errs[5,2] was the smallest
m <- which(abs(calib_errs) == min(abs(calib_errs)),arr.ind = TRUE) # was 5,2

c(m[1], m[2])

adjust_vals[5] # adjustment: 0
adjust_vals[2] # adjustment: -1.5

# Step 3: Update global_params to reflect adjustments (not shown)
calib_assist3(global_params)

# Step 4: Repeat until Table 3 errors are sufficiently small

