---
title: "Data Generating Mechanism Testing"
output: pdf_document
---


```{r, include=FALSE}
library(boot)
library(Rlab)
source("HSR_simulation_fn.R", local = knitr::knit_global())
options(digits=3)
```

We create a single instantiation of the simulation in this block: 

```{r}
df <- make_regions(global_params)
head(df, 2)
dim(df)
df <- tibble::as_tibble(df)
```


Here, I test our ability to estimate the PATT (using 3 estimators) and also calculate the true PATT: 

```{r}
estimate_patt(df)
true_patt(df)
```

Below, I print out simulated results of probabilities we have from the literature that we can use to help calibrate our parameters. 

```{r, echo=F}
# Parameter calibration

# Proportion Black benes, SSP, system, and treated in CPC+ and non-CPC+ regions
attributes_by_S <- df %>% 
  group_by(S) %>% 
  summarise("P(B=1 | S)" = mean(b),
            "P(SSP | S)" = mean(X1),
            "P(system | S)" = mean(X2),
            "P(A | S)" = mean(A)
            ) 

# proportion Black in CPC+ and non-CPC+ participants within CPC+ regions
race_by_participation <- df %>% 
  filter(S==1) %>% 
  group_by(A) %>%
  summarise("P(B=1 | S=1,A)" = mean(b)
            ) 

# Proportion treated in SSP, in system, and overall
prop_treated <- bind_cols(
  (
    df %>% 
      filter(S==1,X1==1) %>% 
      summarise(prop_SSP_treated = mean(A)) ),
  (
    df %>% 
      filter(S==1,X2==1) %>% 
      summarise(prop_sys_treated = mean(A)) ),
  (
    df %>% summarise(prop_treated = mean(A))
  )
  ) %>% 
  `colnames<-`(c("P(A=1 | SSP=1, S=1)", "P(A=1 | sys=1, S=1)", "P(A=1)"))

knitr::kable(attributes_by_S, caption = "B, SSP, System, and A by CPC+ or non-CPC+ region")
knitr::kable(race_by_participation, caption = "Race by CPC+ Participation")
knitr::kable(prop_treated, caption = "Proportion of CPC+ Participation (in SSP, System, and Overall)")

```


Diff-in-diff code

```{r}
df_long <- gather(df, time, Y, Yb.pre:Yb.post)
df_long$time[df_long$time=="Yb.pre"] <- 0
df_long$time[df_long$time=="Yb.post"] <- 1

lm.1 <- lm(Y ~ A + time + A * time + 
                  X1+X2,
                data = df_long %>% filter(S==1) )

# Effect of CPC+ participation on expenditures
lm.1$coefficients["A"]
```

```{r, warning = F}
# Plotting DiD; code adapted from https://rpubs.com/andrewheiss/did

plot_data <- df_long %>% 
  mutate(A = factor(A, labels = c("non-CPC+ participant", "CPC+ participant")),
         time = factor(time, labels = c("Pre-period", "Post-period"))) %>% 
  group_by(A, time) %>% 
  summarize(mean_Y = mean(Y),
            se_Y = sd(Y) / sqrt(n()),
            upper = mean_Y + (-1.96 * se_Y),
            lower = mean_Y + (1.96 * se_Y)) 

ggplot(plot_data, aes(x = time, y = mean_Y, color = A)) +
  geom_pointrange(aes(ymin = lower, ymax = upper), size = 1) + 
  geom_line(aes(group = A))
```


```{r,include=F}
# Drafting parameter test graphs (TO-DO: overlay on one graph)
par(mfrow=c(1,2))
hist(df[df$S==1,]$b, main = "Hist of b, CPC+ regions")
hist(df[df$S==0,]$b, main = "Hist of b, non-CPC+ regions")

```

