---
title: "Data Generating Mechanism Testing"
output: pdf_document
---

```{r, include=FALSE}
library(boot)
library(Rlab)
library(tidyverse)

#library(ramify)
options(digits=3)
source("HSR_simulation_fn.R", local = knitr::knit_global())

```

We create a single instantiation of the simulation in this block: 

```{r}
global_params <- data.frame(
  x1.r = -.617, 
  x2.r = -.715,
  phi.1= -.18, phi.2=-.06, 
  
  q= -1.38,
  om.1= -.165,
  om.2= -3.2,
  om.3= -.235,
  
  H = 0, sigma.H = 0.02,
  psi.1=0, 
  psi.2 =0,
  psi.3 = 0,
  
  theta.P = -68.5, sigma.P =0, 
  gamma.3=-92, 
  gamma.4 = 206, 
  gamma.5 = -87,
  
  beta.0 = -3.05,
  beta.3=0,
  beta.4 = .839,
  beta.5 = 1.17,
  beta.6 = .778, 
  
  alpha.0 = 10100,
  alpha.1 = 46500 , 
  alpha.2 = 600,
  alpha.3 = 12,
  
  P= 1200 # number of practices in a region
  
)
```

Here, I test our ability to estimate the PATT (using 3 estimators) and also calculate the true PATT: 

```{r}
df <- make_regions(global_params)
df <- tibble::as_tibble(df)
estimate_patt(df)
true_patt(df)
```


DID EXAMPLE IN-SAMPLE: 

Running diff-in-diff in-sample: 

```{r}
lm.did(df,plot=T)
plot.did(df)
```

Assumption violations:

```{r}
# Assumption 11 violation
viol_11 <- global_params
viol_11$psi.1 <- 2
viol_11$psi.2 <- 1
viol_11$psi.3 <- 1
viol_11$beta.3 <- .5

df <- make_regions(viol_11)
df <- tibble::as_tibble(df)

# Looking at overlap of joint distribution of W and U between S=0, 1
p <- ggplot( df, aes(x=U, color=factor(S, levels = c("0","1")),fill=factor(S, levels = c("0","1")))) + 
  geom_density(alpha=.3)
p
p + facet_wrap(~W)

df %>% filter(W==1) %>% select(U) %>% summary()

# Looking at U between A=0, 1
p <- ggplot( df, aes(x=U, color=factor(A, levels = c("0","1")),fill=factor(A, levels = c("0","1")))) + 
  geom_density(alpha=.3)
p

```

```{r}
p <- ggplot( df, aes(x=U, color=factor(W),fill=factor(W))) + 
  geom_density(alpha=.3)
p
p + facet_wrap(~S)
```

```{r}
# Assumption 11 violation
viol_11 <- global_params
viol_11$psi.1 <- 2
# delta ~ S * W

df <- make_regions(viol_11)
df <- tibble::as_tibble(df)

p <- ggplot( df, aes(x=U, color=factor(S, levels = c("0","1")),fill=factor(S, levels = c("0","1")))) + 
  geom_density(alpha=.3)
p
```



```{r}
results <- sim_plot_patt(global_params,"psi.1",c(-.1,0,.1),nsim=5)
plot_patt(results, var_name = "psi.1")
```

```{r}
p <- c( .345)
log(p/(1-p))

q <- c( 0.00001) 
log( (q*(1-p))/(p*(1-q)) )
```



