---
title: "Simulation calibration process notebook"
output: html_notebook
---

```{r, include=FALSE}
library(boot)
library(Rlab)
library(tidyverse)
#library(ramify)
options(digits=3)

source("HSR_simulation_fn.R", local = knitr::knit_global())
source("HSR_calib_fn.R", local = knitr::knit_global())
df <- make_regions(global_params)
df <- tibble::as_tibble(df)
```

CALIBRATION

Calibrating first set of parameters:

```{r}

for(n in 1:3){
  start_params <- calib_table1(start_params)  
  print(calib_assist1(start_params))
}

```


```{r}
# Exploring the relationship between om.1/om.2 and different summary statistics

# Scenario: Fewer Black patients in SSP/system hospitals
new_params$om.1= -.165
new_params$om.2= -.097
#new_params$beta.4 = .809
#new_params$beta.5 = 1.17

df %>% 
  filter(S==1) %>% group_by(X1) %>% 
  #group_by(S) %>%
  summarise(prob_B = mean(b))

df %>% 
  filter(S==1) %>% group_by(X2) %>% 
  #group_by(S) %>%
  summarise(prob_B = mean(b))

df %>% 
  filter(S==1) %>% group_by(A) %>% 
  #group_by(S) %>%
  summarise(prob_SSP = mean(X1))

```

Now calibrating second table of parameters: 

```{r}
new_params = global_params
calib_assist2(new_params)

#Search for best adjustment for beta.5
for(adjust1 in seq(0,.5,.1) ){
  new_params$beta.5= global_params$beta.5 + adjust1
  print(c(adjust1, calib_assist2(new_params)[3],  calib_assist2(new_params)[4]))
}



```

Calibrating table 3: 

```{r}
# Goal: minimize P(B=1|S=1, A=0), P(B=1|S=1, A=1) summed abs error

new_params = global_params

# Now searching for the best adjustment of om.1/om.2 simultaneously, 
# to try to adjust them at similar scales. 
# Not shown: re-running with different adjust_vals sequences
# Note that global_params is now updated with the adjustment, 
# so the sequence below will not really make sense

adjust_vals <- seq(-2,1,.5 )
n <- length(adjust_vals)
calib_errs <- matrix(NA, nrow = n, ncol = n)
for(i in c(1:n) ){
  for(j in c(1:n) ){
    new_params$om.1= global_params$om.1 + adjust_vals[i]
    new_params$om.2 = global_params$om.2 + adjust_vals[j]
    
    # minimizing summed absolute error of both targets
    calib_errs[i,j] = abs(calib_assist3(new_params)[1,2])+abs(calib_assist3(new_params)[2,2])
  }
}

# In the above example round of adjustment (with an outdated global_params),
# we found that calib_errs[5,2] was the smallest
m <- which(abs(calib_errs) == min(abs(calib_errs)),arr.ind = TRUE) # was 5,2

c(m[1], m[2])

adjust_vals[5] # adjustment: 0
adjust_vals[2] # adjustment: -1.5

# Not shown: updating global_params to reflect adjustments
calib_assist3(global_params)

```

```{r}
df %>% 
  filter(S==1)%>%
  group_by(X1) %>% 
  summarise(mean_B = mean(b))

df %>% 
  filter(S==1)%>%
  group_by(X2) %>% 
  summarise(mean_B = mean(b))
```

Calibrating to JAMA paper outcomes: 

```{r}
new_params = global_params
new_params$theta.P = global_params$theta.P +7.5
df <- make_regions(new_params)
lm.did(df,plot=T)
```

Below, I print out simulated results of probabilities we have from the literature that we can use to help calibrate our parameters. 

```{r, echo=F}
# Parameter calibration

# Proportion Black benes, SSP, system, and treated in CPC+ and non-CPC+ regions
attributes_by_S <- df %>% 
  group_by(S) %>% 
  summarise("P(B=1 | S)" = mean(b),
            "sd1"=sd(b),
            "P(SSP=1 | S)" = mean(X1),
            "sd2"=sd(X1),
            "P(system=1 | S)" = mean(X2),
            "sd3"=sd(X2),
            "P(A=1 | S)" = mean(A),
            "sd4"=sd(A)
            ) 

# proportion Black in CPC+ and non-CPC+ participants within CPC+ regions
race_by_participation <- df %>% 
  filter(S==1) %>% 
  group_by(A) %>%
  summarise("P(B=1 | S=1,A)" = mean(b),
            "sd" = sd(b)
            ) 

# Proportion treated in SSP, in system, and overall
prop_treated <- bind_cols(
  (
    df %>% 
      filter(S==1,X1==0) %>% 
      summarise(prop_noSSP_treated = mean(A), sd1 = sd(A)) ),
  (
    df %>% 
      filter(S==1,X1==1) %>% 
      summarise(prop_SSP_treated = mean(A), sd2 = sd(A) ) ),
  (
    df %>% 
      filter(S==1,X2==0) %>% 
      summarise(prop_nosys_treated = mean(A), sd3 = sd(A)) ),
  (
    df %>% 
      filter(S==1,X2==1) %>% 
      summarise(prop_sys_treated = mean(A), sd4 = sd(A)) )
  ) %>% 
  `colnames<-`(c("P(A=1 | SSP=0, S=1)","sd1", "P(A=1 | SSP=1, S=1)", "sd2","P(A=1| sys=0, S=1)", "sd3","P(A=1 | sys=1, S=1)","sd4"))

knitr::kable(attributes_by_S, caption = "B, SSP, System, and A by CPC+ or non-CPC+ region")
knitr::kable(prop_treated, caption = "Proportion of CPC+ Participation by System/SSP status")
knitr::kable(race_by_participation, caption = "Race by CPC+ Participation")

```


